[pytest]
pythonpath = services/auth-service services/model-service services/training-service services/training-worker services/prediction-service services/api-gateway
norecursedirs = services/auth-service/app services/model-service/app services/training-service/app services/training-worker/app services/prediction-service/app services/api-gateway/app
